### PR TITLE
OrderIsExported is not set to True after job execution

### PR DESCRIPTION
**Pull request by DWDBE**

### CODE REVIEW

**Comment by frederik5480** [comment]
How come these changes fixes the issue?

**Comment by DWDBE** [comment]
> How come these changes fixes the issue?

Because the connection.State is set to Closed and the line connection.BeginTransaction was throwing an exception in that case, so opening the closed connection before starting transaction fixes the issue.
There was also a problem with sql generated for the SourceReader but it is a different issue/not related to this bug

**Comment by DWDBE** [comment]
> > > How come these changes fixes the issue?
> > 
> > 
> > Because the connection.State is set to Closed and the line connection.BeginTransaction was throwing an exception in that case, so opening the closed connection before starting transaction fixes the issue. There was also a problem with sql generated for the SourceReader but it is a different issue/not related to this bug
> 
> That makes sense. I'm wondering about the change to the sql though, as that would break functionality with the virtual columns used in conditionals, as the sql won't be valid and won't be able to filter on those if it's not wrapped in another select. What bug/issue is it specifically you're trying to solve with this change?

Sure thing, it is a standard simple job with running OrderProvider as a source with selecting the checkboxes for exporting only not exported and completed orders, so the query generated looks like that:
**select * from (**
  SELECT [OrderId], [AccessUserExternalId] as [OrderCustomerAccessUserExternalId] FROM [dbo].[EcomOrders] left join dbo.AccessUser on OrderCustomerAccessUserID = AccessUserID) 
  **AS innerTable** 
  where ([OrderIsExported] = 0 OR [OrderIsExported] IS NULL) AND [OrderCart] != 1  AND [OrderComplete] = 1
  
  Marked text is causing errors for the query, this code was added by @MatthiasSort  but it simply does not work.
  
  So I removed it and now the generated query runs just fine and it also works with the conditions:
  SELECT [OrderId], [AccessUserExternalId] as [OrderCustomerAccessUserExternalId] FROM [dbo].[EcomOrders] left join dbo.AccessUser on OrderCustomerAccessUserID = AccessUserID  where ([OrderIsExported] = 0 OR [OrderIsExported] IS NULL) AND [OrderCart] != 1  AND [OrderComplete] = 1

**Comment by MatthiasSort** [comment]
> > > > How come these changes fixes the issue?
> > > 
> > > 
> > > Because the connection.State is set to Closed and the line connection.BeginTransaction was throwing an exception in that case, so opening the closed connection before starting transaction fixes the issue. There was also a problem with sql generated for the SourceReader but it is a different issue/not related to this bug
> > 
> > 
> > That makes sense. I'm wondering about the change to the sql though, as that would break functionality with the virtual columns used in conditionals, as the sql won't be valid and won't be able to filter on those if it's not wrapped in another select. What bug/issue is it specifically you're trying to solve with this change?
> 
> Sure thing, it is a standard simple job with running OrderProvider as a source with selecting the checkboxes for exporting only not exported and completed orders, so the query generated looks like that: **select * from (** SELECT [OrderId], [AccessUserExternalId] as [OrderCustomerAccessUserExternalId] FROM [dbo].[EcomOrders] left join dbo.AccessUser on OrderCustomerAccessUserID = AccessUserID) **AS innerTable** where ([OrderIsExported] = 0 OR [OrderIsExported] IS NULL) AND [OrderCart] != 1 AND [OrderComplete] = 1
> 
> Marked text is causing errors for the query, this code was added by @MatthiasSort but it simply does not work.
> 
> So I removed it and now the generated query runs just fine and it also works with the conditions: SELECT [OrderId], [AccessUserExternalId] as [OrderCustomerAccessUserExternalId] FROM [dbo].[EcomOrders] left join dbo.AccessUser on OrderCustomerAccessUserID = AccessUserID where ([OrderIsExported] = 0 OR [OrderIsExported] IS NULL) AND [OrderCart] != 1 AND [OrderComplete] = 1

but if you use the "alias" column in a where-clause it fails
image

**Comment by DWDBE** [comment]
> > > > > How come these changes fixes the issue?
> > > > 
> > > > 
> > > > Because the connection.State is set to Closed and the line connection.BeginTransaction was throwing an exception in that case, so opening the closed connection before starting transaction fixes the issue. There was also a problem with sql generated for the SourceReader but it is a different issue/not related to this bug
> > > 
> > > 
> > > That makes sense. I'm wondering about the change to the sql though, as that would break functionality with the virtual columns used in conditionals, as the sql won't be valid and won't be able to filter on those if it's not wrapped in another select. What bug/issue is it specifically you're trying to solve with this change?
> > 
> > 
> > Sure thing, it is a standard simple job with running OrderProvider as a source with selecting the checkboxes for exporting only not exported and completed orders, so the query generated looks like that: **select * from (** SELECT [OrderId], [AccessUserExternalId] as [OrderCustomerAccessUserExternalId] FROM [dbo].[EcomOrders] left join dbo.AccessUser on OrderCustomerAccessUserID = AccessUserID) **AS innerTable** where ([OrderIsExported] = 0 OR [OrderIsExported] IS NULL) AND [OrderCart] != 1 AND [OrderComplete] = 1
> > Marked text is causing errors for the query, this code was added by @MatthiasSort but it simply does not work.
> > So I removed it and now the generated query runs just fine and it also works with the conditions: SELECT [OrderId], [AccessUserExternalId] as [OrderCustomerAccessUserExternalId] FROM [dbo].[EcomOrders] left join dbo.AccessUser on OrderCustomerAccessUserID = AccessUserID where ([OrderIsExported] = 0 OR [OrderIsExported] IS NULL) AND [OrderCart] != 1 AND [OrderComplete] = 1
> 
> but if you use the "alias" column in a where-clause it fails image image

there is no such a column in the source schema and also not available in the conditions:

image

image

**Comment by DWDBE** [comment]
> > > > > > How come these changes fixes the issue?
> > > > > 
> > > > > 
> > > > > Because the connection.State is set to Closed and the line connection.BeginTransaction was throwing an exception in that case, so opening the closed connection before starting transaction fixes the issue. There was also a problem with sql generated for the SourceReader but it is a different issue/not related to this bug
> > > > 
> > > > 
> > > > That makes sense. I'm wondering about the change to the sql though, as that would break functionality with the virtual columns used in conditionals, as the sql won't be valid and won't be able to filter on those if it's not wrapped in another select. What bug/issue is it specifically you're trying to solve with this change?
> > > 
> > > 
> > > Sure thing, it is a standard simple job with running OrderProvider as a source with selecting the checkboxes for exporting only not exported and completed orders, so the query generated looks like that: **select * from (** SELECT [OrderId], [AccessUserExternalId] as [OrderCustomerAccessUserExternalId] FROM [dbo].[EcomOrders] left join dbo.AccessUser on OrderCustomerAccessUserID = AccessUserID) **AS innerTable** where ([OrderIsExported] = 0 OR [OrderIsExported] IS NULL) AND [OrderCart] != 1 AND [OrderComplete] = 1
> > > Marked text is causing errors for the query, this code was added by @MatthiasSort but it simply does not work.
> > > So I removed it and now the generated query runs just fine and it also works with the conditions: SELECT [OrderId], [AccessUserExternalId] as [OrderCustomerAccessUserExternalId] FROM [dbo].[EcomOrders] left join dbo.AccessUser on OrderCustomerAccessUserID = AccessUserID where ([OrderIsExported] = 0 OR [OrderIsExported] IS NULL) AND [OrderCart] != 1 AND [OrderComplete] = 1
> > 
> > 
> > but if you use the "alias" column in a where-clause it fails image image
> 
> there is no such a column in the source schema and also not available in the conditions:
> 
> image image

Ok, how now found it in the OrderLines table schema and conditions, so will look on how to make it to work properly for all cases 👍

**Review by MatthiasSort — APPROVED** [review]
Working with alias-select-column in the conditionals and all test jobs ran without errors :)

**Review by frederik5480 — APPROVED** [review]

**Pull request merged**
